import os

# Generated by ChatGPT. curdir on local and streamlit production servers are different.
# This helps return the path of files irrespective of curdir mount location
def get_file_path(target_subpath: str) -> str:
    # Get the current working directory
    current_dir = os.path.abspath(os.curdir)

    # Define the base path relative to the root of the project
    base_subpath = os.path.normpath('Recommendation/streamlit_recommendation')

    # Check if the current working directory already includes the base path
    if base_subpath in current_dir:
        # If so, get the relative path from the current directory
        relative_path = os.path.relpath(target_subpath, current_dir)
        file_path = os.path.join(current_dir, relative_path)
    else:
        # Otherwise, construct the path relative to the base path
        file_path = os.path.join(current_dir, base_subpath, target_subpath)
    
    return os.path.normpath(file_path)